// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFd6LeTAz12KabjstWOZv48BSyyF9nEgc',
    appId: '1:835109086614:android:abe9683dcb340d0715e9b7',
    messagingSenderId: '835109086614',
    projectId: 'literature-cad31',
    databaseURL: 'https://literature-cad31.firebaseio.com',
    storageBucket: 'literature-cad31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4aR4sAkYdELLcrI2KEPhi1LP86-mdZj8',
    appId: '1:835109086614:ios:d029e09442b677aa15e9b7',
    messagingSenderId: '835109086614',
    projectId: 'literature-cad31',
    databaseURL: 'https://literature-cad31.firebaseio.com',
    storageBucket: 'literature-cad31.appspot.com',
    iosClientId: '835109086614-lqro7vv996uq12m9f88rke37rf294klc.apps.googleusercontent.com',
    iosBundleId: 'com.letovooutside.letovoOutside',
  );
}
